.pc
.TH syscon.raku 1 2024-01-08
.SH Syscon, sc
.SS Table of Contents
.IP \(bu 2m
NAME [#name]
.IP \(bu 2m
AUTHOR [#author]
.IP \(bu 2m
VERSION [#version]
.IP \(bu 2m
TITLE [#title]
.IP \(bu 2m
SUBTITLE [#subtitle]
.IP \(bu 2m
COPYRIGHT [#copyright]
.IP \(bu 2m
Introduction [#introduction]
.RS 2n
.IP \(bu 2m
Motivations [#motivations]
.RE
.IP \(bu 2m
USAGE [#usage]
.RS 2n
.IP \(bu 2m
The actual work horses of the library [#the-actual-work-horses-of-the-library]
.RE
.RS 2n
.RS 2n
.IP \(bu 2m
sc ssh [#sc-ssh]
.RE
.RE
.RS 2n
.RS 2n
.IP \(bu 2m
sc ping [#sc-ping]
.RE
.RE
.RS 2n
.RS 2n
.IP \(bu 2m
sc get home [#sc-get-home]
.RE
.RE
.RS 2n
.RS 2n
.IP \(bu 2m
sc put home [#sc-put-home]
.RE
.RE
.RS 2n
.IP \(bu 2m
Utility functions [#utility-functions]
.RE
.RS 2n
.RS 2n
.IP \(bu 2m
sc edit configs [#sc-edit-configs]
.RE
.RE
.RS 2n
.RS 2n
.IP \(bu 2m
sc list keys [#sc-list-keys]
.RE
.RE
.RS 2n
.RS 2n
.IP \(bu 2m
sc list by all [#sc-list-by-all]
.RE
.RE
.RS 2n
.RS 2n
.IP \(bu 2m
sc list trash [#sc-list-trash]
.RE
.RE
.RS 2n
.RS 2n
.IP \(bu 2m
sc trash [#sc-trash]
.RE
.RE
.RS 2n
.RS 2n
.IP \(bu 2m
sc empty trash [#sc-empty-trash]
.RE
.RE
.RS 2n
.RS 2n
.IP \(bu 2m
sc undelete [#sc-undelete]
.RE
.RE
.RS 2n
.RS 2n
.IP \(bu 2m
sc stats [#sc-stats]
.RE
.RE
.RS 2n
.RS 2n
.IP \(bu 2m
sc statistics [#sc-statistics]
.RE
.RE
.RS 2n
.RS 2n
.IP \(bu 2m
sc add [#sc-add]
.RE
.RE
.RS 2n
.RS 2n
.IP \(bu 2m
sc delete [#sc-delete]
.RE
.RE
.RS 2n
.RS 2n
.IP \(bu 2m
sc del [#sc-del]
.RE
.RE
.RS 2n
.RS 2n
.IP \(bu 2m
sc comment [#sc-comment]
.RE
.RE
.RS 2n
.RS 2n
.IP \(bu 2m
backup db [#backup-db]
.RE
.RE
.RS 2n
.RS 2n
.IP \(bu 2m
sc restore db [#sc-restore-db]
.RE
.RE
.RS 2n
.RS 2n
.IP \(bu 2m
sc menu restore db [#sc-menu-restore-db]
.RE
.RE
.RS 2n
.RS 2n
.IP \(bu 2m
USAGE [#fred]
.RE
.RE
.RS 2n
.RS 2n
.IP \(bu 2m
USAGE [#wilma]
.RE
.RE
.RS 2n
.RS 2n
.IP \(bu 2m
USAGE [#usage]
.RE
.RE
.RS 2n
.RS 2n
.IP \(bu 2m
USAGE [#usage]
.RE
.RE
.RS 2n
.RS 2n
.IP \(bu 2m
USAGE [#usage]
.RE
.RE
.RS 2n
.RS 2n
.IP \(bu 2m
USAGE [#usage]
.RE
.RE
.RS 2n
.RS 2n
.IP \(bu 2m
USAGE [#usage]
.RE
.RE
.RS 2n
.RS 2n
.IP \(bu 2m
ssh(…) [#ssh]
.RE
.RE
.RS 2n
.RS 2n
.IP \(bu 2m
ping(…) [#ping]
.RE
.RE
.RS 2n
.RS 2n
.IP \(bu 2m
_get(…) [#_get] or on raku\&.land _get [#-get]
.RE
.RE
.RS 2n
.RS 2n
.IP \(bu 2m
_put [#usage] or on raku\&.land _get [#-put]
.RE
.RE
.SH "NAME"
syscon, sc
.SH "AUTHOR"
Francis Grizzly Smit (grizzly@smit\&.id\&.au)
.SH "VERSION"
v0\&.1\&.18
.SH "TITLE"
syscon, sc
.SH "SUBTITLE"
A module \fBSyscon\fR and a program \fBsyscon\fR or \fBsc\fR for short, which keeps tarck of assorted servers and helps to connect to them\&.
.SH "COPYRIGHT"
LGPL V3\&.0+ LICENSE [/LICENSE]
.SH Introduction

A module \fBSyscon\fR and a program \fBsyscon\fR or \fBsc\fR for short, which keeps tarck of assorted servers and helps to connect to them\&.

Top of Document [#table-of-contents]
.SS Motivations

I have to keep track of many servers (> 100) but who can remember all the host names, and ports?? That is where this app comes in I can connect to a server by ssh by\&.

.RS 4m
.EX
$ syscon\&.raku ssh <key>


.EE
.RE
.P
or for short

.RS 4m
.EX
$ sc ssh <key>


.EE
.RE
.P
Equally you can use

.RS 4m
.EX
$ sc put home <key> <files> ……


.EE
.RE
.P
To run 

.RS 4m
.EX
$ scp \-P $port <files> …… $host:


.EE
.RE
.IP \(bu 2m
Where 
.RS 2n
.IP \(bu 2m
\fB$host\fR is generally something like \fBusername@example\&.com\fR
.RE
.RS 2n
.IP \(bu 2m
\fB$port\fR is a port number\&.
.RE
.RS 2n
.IP \(bu 2m
\fBkey\fR is the key to retrieve the host and port form the server\&.
.RE
.RS 2n
.RS 2n
.IP \(bu 2m
It's put home because I may add put <other\-place> at a later date\&.
.RE
.RE

Top of Document [#table-of-contents]

This is the app, you can find the modules docs here [/docs/Syscon.md]
.SS USAGE

.RS 4m
.EX
sc \-\-help

Usage:                                                                                                                                                
  sc ssh <key>
  sc ping <key>
  sc get home <key>  [<args> \&.\&.\&.] [\-r|\-\-recursive] [\-t|\-\-to=<Str>]
  sc put home <key>  [<args> \&.\&.\&.] [\-r|\-\-recursive] [\-t|\-\-to=<Str>]
  sc edit configs
  sc list keys  [<prefix>]  [\-c|\-\-color|\-\-colour] [\-s|\-\-syntax] [\-l|\-\-page\-length[=Int]] [\-p|\-\-pattern=<Str>] [\-e|\-\-ecma\-pattern=<Str>]
  sc list by all  [<prefix>]  [\-c|\-\-color|\-\-colour] [\-s|\-\-syntax] [\-l|\-\-page\-length[=Int]] [\-p|\-\-pattern=<Str>] [\-e|\-\-ecma\-pattern=<Str>]
  sc list trash  [<prefix>]  [\-c|\-\-color|\-\-colour] [\-s|\-\-syntax] [\-l|\-\-page\-length[=Int]] [\-p|\-\-pattern=<Str>] [\-e|\-\-ecma\-pattern=<Str>]
  sc trash   [<keys> \&.\&.\&.]
  sc empty trash
  sc undelete   [<keys> \&.\&.\&.]
  sc stats  [<prefix>]  [\-c|\-\-color|\-\-colour] [\-s|\-\-syntax] [\-p|\-\-pattern=<Str>] [\-e|\-\-ecma\-pattern=<Str>]
  sc statistics  [<prefix>]  [\-c|\-\-color|\-\-colour] [\-s|\-\-syntax] [\-p|\-\-pattern=<Str>] [\-e|\-\-ecma\-pattern=<Str>]
  sc add <key> <host> [<port>]  [\-s|\-\-set|\-\-force] [\-c|\-\-comment=<Str>]
  sc delete   [<keys> \&.\&.\&.] [\-d|\-\-delete|\-\-do\-not\-trash]
  sc del   [<keys> \&.\&.\&.] [\-d|\-\-delete|\-\-do\-not\-trash]
  sc comment <key> <comment>
  sc alias <key> <target>   [\-s|\-\-set|\-\-force] [\-d|\-\-really\-force|\-\-overwrite\-hosts] [\-c|\-\-comment=<Str>]
  sc backup db    [\-w|\-\-win\-format|\-\-use\-windows\-formating]
  sc restore db  [<restore\-from>]
  sc menu restore db  [<message>]  [\-c|\-\-color|\-\-colour] [\-s|\-\-syntax]
  sc list db backups  [<prefix>]  [\-c|\-\-color|\-\-colour] [\-s|\-\-syntax] [\-l|\-\-page\-length[=Int]] [\-p|\-\-pattern=<Str>] [\-e|\-\-ecma\-pattern=<Str>]
  sc list editors    [\-f|\-\-prefix=<Str>] [\-c|\-\-color|\-\-colour] [\-s|\-\-syntax] [\-l|\-\-page\-length[=Int]] [\-p|\-\-pattern=<Str>] [\-e|\-\-ecma\-pattern=<Str>]
  sc editors stats  [<prefix>]  [\-c|\-\-color|\-\-colour] [\-s|\-\-syntax] [\-l|\-\-page\-length[=Int]] [\-p|\-\-pattern=<Str>] [\-e|\-\-ecma\-pattern=<Str>]
  sc list editors backups  [<prefix>]  [\-c|\-\-color|\-\-colour] [\-s|\-\-syntax] [\-l|\-\-page\-length[=Int]] [\-p|\-\-pattern=<Str>] [\-e|\-\-ecma\-pattern=<Str>]
  sc backup editors    [\-w|\-\-use\-windows\-formatting]
  sc restore editors <restore\-from>
  sc set editor <editor> [<comment>]
  sc set override GUI_EDITOR <value> [<comment>]
  sc menu restore editors  [<message>]  [\-c|\-\-color|\-\-colour] [\-s|\-\-syntax]
  sc tidy file
  sc sort file
  sc show file    [\-c|\-\-color|\-\-colour]
  sc help   [<args> \&.\&.\&.] [\-n|\-\-nocolor|\-\-nocolour] [\-\-<named\-args>=\&.\&.\&.]


.EE
.RE
.P
!image not available here go to the github page [/docs/images/usage.png]

Top of Document [#table-of-contents]
.SS The actual work horses of the library
.SS sc ssh

Runs

.RS 4m
.EX
ssh \-p $port $host


.EE
.RE
.P
by the \fBssh(…)\fR function defined in \fBSyscon\&.rakumod\fR\&.

.RS 4m
.EX
22:22:06 θ76° grizzlysmit@pern:~ $ sc  ssh rak
ssh \-p 22 rakbat\&.local
Welcome to Ubuntu 23\&.10 (GNU/Linux 6\&.5\&.0\-14\-generic x86_64)

 * Documentation:  https://help\&.ubuntu\&.com
 * Management:     https://landscape\&.canonical\&.com
 * Support:        https://ubuntu\&.com/advantage

0 updates can be applied immediately\&.



Last login: Tue Jan  2 23:48:56 2024 from 192\&.168\&.188\&.11
06:55:31 grizzlysmit@rakbat:~ $ 


.EE
.RE
.P
!image not available here go to the github page [/docs/images/sc-ssh.png]

Top of Document [#table-of-contents]
.SS sc ping

Runs

.RS 4m
.EX
7:02:58 θ83° grizzlysmit@pern:~ 7m29s $ sc ping kil
ping killashandra\&.local
PING killashandra\&.local (192\&.168\&.188\&.11) 56(84) bytes of data\&.
64 bytes from killashandra\&.local (192\&.168\&.188\&.11): icmp_seq=1 ttl=64 time=0\&.285 ms
64 bytes from killashandra\&.local (192\&.168\&.188\&.11): icmp_seq=2 ttl=64 time=0\&.249 ms
64 bytes from killashandra\&.local (192\&.168\&.188\&.11): icmp_seq=3 ttl=64 time=0\&.242 ms
64 bytes from killashandra\&.local (192\&.168\&.188\&.11): icmp_seq=4 ttl=64 time=0\&.253 ms
64 bytes from killashandra\&.local (192\&.168\&.188\&.11): icmp_seq=5 ttl=64 time=0\&.274 ms
64 bytes from killashandra\&.local (192\&.168\&.188\&.11): icmp_seq=6 ttl=64 time=0\&.273 ms
64 bytes from killashandra\&.local (192\&.168\&.188\&.11): icmp_seq=7 ttl=64 time=0\&.226 ms
64 bytes from killashandra\&.local (192\&.168\&.188\&.11): icmp_seq=8 ttl=64 time=0\&.831 ms
64 bytes from killashandra\&.local (192\&.168\&.188\&.11): icmp_seq=9 ttl=64 time=0\&.272 ms
64 bytes from killashandra\&.local (192\&.168\&.188\&.11): icmp_seq=10 ttl=64 time=0\&.264 ms
64 bytes from killashandra\&.local (192\&.168\&.188\&.11): icmp_seq=11 ttl=64 time=0\&.227 ms
64 bytes from killashandra\&.local (192\&.168\&.188\&.11): icmp_seq=12 ttl=64 time=0\&.263 ms
64 bytes from killashandra\&.local (192\&.168\&.188\&.11): icmp_seq=13 ttl=64 time=0\&.255 ms
64 bytes from killashandra\&.local (192\&.168\&.188\&.11): icmp_seq=14 ttl=64 time=0\&.258 ms
64 bytes from killashandra\&.local (192\&.168\&.188\&.11): icmp_seq=15 ttl=64 time=0\&.234 ms
64 bytes from killashandra\&.local (192\&.168\&.188\&.11): icmp_seq=16 ttl=64 time=0\&.220 ms
^C
\-\-\- killashandra\&.local ping statistics \-\-\-
16 packets transmitted, 16 received, 0% packet loss, time 15337ms
rtt min/avg/max/mdev = 0\&.220/0\&.289/0\&.831/0\&.141 ms



.EE
.RE
.IP \(bu 2m
Where
.RS 2n
.IP \(bu 2m
\fB$key\fR a key in the db\&.
.RE

!image not available here go to the github page [/docs/images/ping.png]

by the \fBsc ping $key\fR

.RS 4m
.EX
multi sub MAIN('ping', Str:D $key \-\-> int){
    if ping($key) {
        return 0;
    } else {
        return 1;
    }
}


.EE
.RE
.P
Top of Document [#table-of-contents]
.SS sc get home

Get some files on the remote system and deposit them here (in the directory the user is currently in)\&.

.RS 4m
.EX
$ sc get home $key \-\-to=$to \-\-recursive $files\-on\-remote\-system……


.EE
.RE
.IP \(bu 2m
Where
.RS 2n
.IP \(bu 2m
\fB$key\fR The key of the host to get files from\&.
.RE
.RS 2n
.IP \(bu 2m
\fB$to\fR The place to put the files defaults to \fB\&.\fR or here\&.
.RE
.RS 2n
.IP \(bu 2m
\fB\-\-recursive\fR sets the recursive flag so the files will be copied recursively, allowing a whole file sub tree to be copied\&.
.RE
.RS 2n
.IP \(bu 2m
\fB$files\-on\-remote\-system……\fR A list of files on the remote system to copy can be anywhere on the remote system\&.
.RE

e\&.g\&.

.RS 4m
.EX
$ sc get home rak \-\-to=scratch \&.bashrc /etc/hosts 
scp \-P 22 rakbat\&.local:\&.bashrc \&.
\&.bashrc                   100%   11KB   6\&.9MB/s   00:00
scp \-P 22 rakbat\&.local:/etc/hosts \&.
hosts                     100%  313   228\&.8KB/s   00:00


.EE
.RE
.P
!image not available here go to the github page [/docs/images/sc-get-home.png]

Using the \fB_get(…)\fR [#_get] or on raku\&.land \fB_get(…)\fR [#-get] function defined in \fBSyscon\&.rakumod\fR\&.

Top of Document [#table-of-contents]
.SS sc put home

.RS 4m
.EX
$ sc put home $key \-\-to=$to \-\-recursive $files……


.EE
.RE
.IP \(bu 2m
Where
.RS 2n
.IP \(bu 2m
\fB$key\fR is as always the key to identify the host in question\&.
.RE
.RS 2n
.IP \(bu 2m
\fB$to\fR is the place to put the files on the rmote system\&.
.RE
.RS 2n
.IP \(bu 2m
\fB\-\-recursive\fR sets the recursive flag so the files will be copied recursively, allowing a whole file sub tree to be copied\&.
.RE
.RS 2n
.IP \(bu 2m
\fB$files\fR…… is a list of files to copy to the remote server\&.
.RE

.RS 4m
.EX
sc put home kil \-\-to=tmp scratch/bug\&.raku  docs/Syscon\&.1 
scp \-P 22 scratch/bug\&.raku docs/Syscon\&.1 grizzlysmit@killashandra\&.local:tmp
bug\&.raku                                           100% 3303   557\&.3KB/s   00:00
Syscon\&.1                                           100%  485     1\&.0MB/s   00:00


.EE
.RE
.P
!image not available here go to the github page [/docs/images/sc-put-home.png]

Implemented as

.RS 4m
.EX
multi sub MAIN('put', 'home', Str:D $key, Bool :r(:$recursive) = False, *@args \-\-> int){
    if _put('home', $key, :$recursive, |@args) {
        return 0;
    } else {
        return 1;
    }
}


.EE
.RE
.IP \(bu 2m
Where
.RS 2n
.IP \(bu 2m
\fBmulti sub _put('home', Str:D $key, Bool :r(:$recursive) = False, Str:D :$to = '', *@args \-\- Bool) is export\fR> is a function in \fBSysycon\&.rakumod\fR See \fB_put(…)\fR [#_put] or on raku\&.land \fB_put(…)\fR [#-put]\&.
.RE

Top of Document [#table-of-contents]
.SS Utility functions
.SS sc edit configs

.RS 4m
.EX
$ sc edit configs


.EE
.RE
.P
Implemented by the \fBedit\-configs\fR function in the \fBGUI::Editors\&.rakumod\fR module\&. This open your configuration files in your preferred GUI editor, if you have one, if you don't have one of those setup it will try for a good substitute, failing that it will Fail and print an error message\&. 

Do not use this it's for experts only, instead use the \fBset\-*(…)\fR functions below\&.

.RS 4m
.EX
multi sub MAIN('edit', 'configs') returns Int {
   if edit\-configs() {
       exit 0;
   } else {
       exit 1;
   } 
}


.EE
.RE
.P
Top of Document [#table-of-contents]
.SS sc list keys 

.RS 4m
.EX
$ sc list keys \-\-help


.EE
.RE
.P
!image not available here go to the github page [/docs/images/sc-list-keys.png]

Top of Document [#table-of-contents]
.SS sc list by all

.RS 4m
.EX
sc list by all \-\-help


.EE
.RE
.P
!image not available here go to the github page [/docs/images/sc-list-by-all.png]

.RS 4m
.EX
sc list by all


.EE
.RE
.P
!image not available here go to the github page [/docs/images/sc-list-by-all-pattern.png]

Top of Document [#table-of-contents]
.SS sc list trash

.RS 4m
.EX
sc list trash \-\-help


.EE
.RE
.P
!image not available here go to the github page [/docs/images/sc-list-trash--help.png]

.RS 4m
.EX
sc list trash \-\-help


.EE
.RE
.P
!image not available here go to the github page [/docs/images/sc-list-trash.png]

Top of Document [#table-of-contents]
.SS sc trash

.RS 4m
.EX
sc trash \-\-help


.EE
.RE
.P
!image not available here go to the github page [/docs/images/sc-trash--help.png]

.RS 4m
.EX
sc trash


.EE
.RE
.P
!image not available here go to the github page [/docs/images/sc-trash.png]

Top of Document [#table-of-contents]
.SS sc empty trash

.RS 4m
.EX
sc empty trash \-\-help


.EE
.RE
.P
!image not available here go to the github page [/docs/images/sc-empty-trash.png]

Top of Document [#table-of-contents]
.SS sc undelete

.RS 4m
.EX
sc undelete \-\-help


.EE
.RE
.P
!image not available here go to the github page [/docs/images/sc-undelete.png]

Top of Document [#table-of-contents]
.SS sc stats

.RS 4m
.EX
sc stats


.EE
.RE
.P
!image not available here go to the github page [/docs/images/sc-stats.png]
.SS sc statistics

An alias of stats see above sc stats [#sc-stats]\&.

Top of Document [#table-of-contents]
.SS sc add

.RS 4m
.EX
sc add <key> <host> [<port>]  [\-s|\-\-set|\-\-force] [\-c|\-\-comment=<Str>] 


.EE
.RE
.IP \(bu 2m
Where
.RS 2n
.IP \(bu 2m
\fB<key>\fR is a unused key unless you use one of \fB\-s|\-\-set|\-\-force\fR in which case it will overwrite the old value\&.
.RE
.RS 2n
.IP \(bu 2m
\fB<host>\fR is a host spec of the form \fBusername@dns\-address\-or\-host\-name\fR\&.
.RE
.RS 2n
.IP \(bu 2m
\fB<port>\fR is a port number, if not present defaults to \fB22\fR\&.
.RE
.RS 2n
.IP \(bu 2m
If \fB\-s\fR, \fB\-\-set\fR or \fB\-\-force\fR is present you can overwrite existing entries use with care\&.
.RE
.RS 2n
.IP \(bu 2m
If \fB\-c\fR or \fB\-\-comment\fR are present then \fB<Str>\fR should be a comment string to go with the entry\&.
.RE
.RS 2n
.RS 2n
.IP \(bu 2m
Example use\&.
.IP
!sc add ex grizzlysmit@example\&.com 344 \-\-comment="an example host" [/docs/images/sc-add.png]
.RE
.RE

Top of Document [#table-of-contents]
.SS sc delete

A command to delete a row in the db i\&.e\&. a key and details, by default it just trashes the key but if \fB\-d\fR, \fB\-\-delete\fR or \fB\-\-do\-not\-trash\fR is present it will really delete\&. 

.RS 4m
.EX
sc delete \-\-help

Usage:                                                                                                                                                
  sc delete [<keys> \&.\&.\&.] [\-d|\-\-delete|\-\-do\-not\-trash]                                          


.EE
.RE
.IP \(bu 2m
Where
.RS 2n
.IP \(bu 2m
\fB[<keys> \&.\&.\&.]\fR is a optional list of keys if none are provided then the command does nothing 
.RE
.RS 2n
.IP \(bu 2m
\fB[\-d|\-\-delete|\-\-do\-not\-trash]\fR is a flag to really delete, not trash them see see [#sc-trash]\&.
.RE
.SS sc del 

An alias for delete 

.RS 4m
.EX
 sc del \-\-help

Usage:                                                                                                                                                
  sc delete [<keys> \&.\&.\&.] [\-d|\-\-delete|\-\-do\-not\-trash]                                                                                                 
  sc del [<keys> \&.\&.\&.] [\-d|\-\-delete|\-\-do\-not\-trash]


.EE
.RE
.P
Top of Document [#table-of-contents]
.SS sc comment

Add or set a comment to a db entry\&. 

.RS 4m
.EX
sc comment \-\-help

Usage:                                                                                                                                                
  sc comment <key> <comment>                                                                                                                          

.EE
.RE
.IP \(bu 2m
Where
.RS 2n
.IP \(bu 2m
\fB<key>\fR An existing key in the db\&.
.RE
.RS 2n
.IP \(bu 2m
\fB<comment>\fR The comment to add\&.
.RE

Top of Document [#table-of-contents]
.SS sc alias

.RS 4m
.EX
sc alias \-\-help

Usage:                                                                                                                                                
  sc alias <key> <target>  [\-s|\-\-set|\-\-force] [\-d|\-\-really\-force|\-\-overwrite\-hosts] [\-c|\-\-comment=<Str>]


.EE
.RE
.IP \(bu 2m
Where
.RS 2n
.IP \(bu 2m
\fB<key>\fR is a new key to add or an exiting one to overwrite if you use \fB\-s\fR, \fB\-\-set\fR or \fB\-\-force\fR\&.
.RE
.RS 2n
.RS 2n
.IP \(bu 2m
\fBNB:\fR \fB\-s\fR, \fB\-\-set\fR or \fB\-\-force\fR only work for \fBaliases\fR to overwrite \fBhosts\fR use \fB\-d\fR, \fB\-\-really\-force\fR or \fB\-\-overwrite\-hosts\fR\&.
.RE
.RE
.RS 2n
.IP \(bu 2m
\fB<target>\fR Either a existing host or alias, it is an error if \fB<target>\fR does not exist\&.
.RE
.RS 2n
.IP \(bu 2m
\fB\-s\fR, \fB\-\-set\fR or \fB\-\-force\fR mean overwrite any existing \fB<key>\fR if it is an alias\&.
.RE
.RS 2n
.IP \(bu 2m
\fB\-d\fR, \fB\-\-really\-force\fR or \fB\-\-overwrite\-hosts\fR means overwrite anything regardless, use with care\&.
.RE

Top of Document [#table-of-contents]
.SS backup db

Backup the file which is the db for this little app, I could use a \fIreal\fR db but as it's just one simple table, I don't need that\&.

.RS 4m
.EX
 sc backup db \-\-help

Usage:
  sc backup db  [\-w|\-\-win\-format|\-\-use\-windows\-formating]


.EE
.RE
.IP \(bu 2m
Where
.RS 2n
.IP \(bu 2m
\fB\-w\fR, \fB\-\-win\-format\fR or \fB\-\-use\-windows\-formating\fR means that the '\fB:\fR' in the date time will be replaced with '\fB\&.\fR' and the '\fB\&.\fR' the decimal point between the seconds and fractions of seconds will be maped to '\fB·\fR'; as widows uses '\fB:\fR' specially\&.
.RE
.RS 2n
.RS 2n
.IP \(bu 2m
under windows the this will always be the case, so you don't need it there\&.
.RE
.RE

Top of Document [#table-of-contents]
.SS sc restore db

.RS 4m
.EX
sc restore db \-\-help

Usage:
  sc restore db [<restore\-from>]


.EE
.RE
.P
Top of Document [#table-of-contents]
.SS sc menu restore db

Restore the db using a menu to make it easy to choose the db backup from the ones available in the configuration directory\&. 

.RS 4m
.EX
sc menu restore db \-\-help

Usage:
  sc menu restore db [<message>]  [\-c|\-\-color|\-\-colour] [\-s|\-\-syntax]


.EE
.RE
.P
Top of Document [#table-of-contents]
