.pc
.TH syscon.raku 1 2023-12-21
.SS Table of Contents
.IP \(bu 2m
NAME [#name]
.IP \(bu 2m
AUTHOR [#author]
.IP \(bu 2m
VERSION [#version]
.IP \(bu 2m
TITLE [#title]
.IP \(bu 2m
SUBTITLE [#subtitle]
.IP \(bu 2m
COPYRIGHT [#copyright]
.IP \(bu 2m
Introduction [#introduction]
.RS 2n
.IP \(bu 2m
Motivations [#motivations]
.RE
.IP \(bu 2m
USAGE [#usage]
.RS 2n
.IP \(bu 2m
The actual work horses of the library [#the-actual-work-horses-of-the-library]
.RE
.RS 2n
.RS 2n
.IP \(bu 2m
sc ssh [#sc-ssh]
.RE
.RE
.RS 2n
.RS 2n
.IP \(bu 2m
sc ping [#sc-ping]
.RE
.RE
.RS 2n
.RS 2n
.IP \(bu 2m
sc get home [#sc-get-home]
.RE
.RE
.RS 2n
.RS 2n
.IP \(bu 2m
sc put home [#sc-put-home]
.RE
.RE
.RS 2n
.IP \(bu 2m
Utility functions [#utility-functions]
.RE
.RS 2n
.RS 2n
.IP \(bu 2m
sc edit configs [#sc-edit-configs]
.RE
.RE
.RS 2n
.RS 2n
.IP \(bu 2m
USAGE [#usage]
.RE
.RE
.RS 2n
.RS 2n
.IP \(bu 2m
USAGE [#usage]
.RE
.RE
.RS 2n
.RS 2n
.IP \(bu 2m
USAGE [#usage]
.RE
.RE
.SH "NAME"
syscon 
.SH "AUTHOR"
Francis Grizzly Smit (grizzly@smit\&.id\&.au)
.SH "VERSION"
v0\&.1\&.18
.SH "TITLE"
syscon
.SH "SUBTITLE"
A module \fBSyscon\fR and a program \fBsyscon\fR or \fBsc\fR for short, which keeps tarck of assorted servers and helps to connect to them\&.
.SH "COPYRIGHT"
LGPL V3\&.0+ LICENSE [https://github.com/grizzlysmit/syscon/blob/main/LICENSE]
.SH Introduction

A module \fBSyscon\fR and a program \fBsyscon\fR or \fBsc\fR for short, which keeps tarck of assorted servers and helps to connect to them\&.

Top of Document [#table-of-contents]
.SS Motivations

I have to keep track of many servers (> 100) but who can remember all the host names, and ports?? That is where this app comes in I can connect to a server by ssh by\&.

.RS 4m
.EX
$ syscon\&.raku ssh <key>


.EE
.RE
.P
or for short

.RS 4m
.EX
$ sc ssh <key>


.EE
.RE
.P
Equally you can use

.RS 4m
.EX
$ sc put home <key> <files> ……


.EE
.RE
.P
To run 

.RS 4m
.EX
$ scp \-P $port <files> …… $host:


.EE
.RE
.IP \(bu 2m
Where 
.RS 2n
.IP \(bu 2m
\fB$host\fR is generally something like \fBusername@example\&.com\fR
.RE
.RS 2n
.IP \(bu 2m
\fB$port\fR is a port number\&.
.RE
.RS 2n
.IP \(bu 2m
\fBkey\fR is the key to retrieve the host and port form the server\&.
.RE
.RS 2n
.RS 2n
.IP \(bu 2m
It's put home because I may add put <other\-place> at a later date\&.
.RE
.RE

Top of Document [#table-of-contents]

This is the app, you can find the modules docs here [https://github.com/grizzlysmit/syscon]
.SS USAGE

.RS 4m
.EX
$ sc \-\-help


.EE
.RE
.P
!https://github\&.com/grizzlysmit/syscon/blob/main/docs/images/usage\&.png

Top of Document [#table-of-contents]
.SS The actual work horses of the library
.SS sc ssh

Runs

.RS 4m
.EX
ssh \-p $port $host


.EE
.RE
.P
by the \fBssh(…)\fR function defined in \fBSyscon\&.rakumod\fR\&.

.RS 4m
.EX
multi sub MAIN('ssh', Str:D $key \-\-> int){
    if ssh($key) {
        return 0;
    } else {
        return 1;
    }
}


.EE
.RE
.P
!https://github\&.com/grizzlysmit/syscon/blob/main/docs/images/sc\-ssh\&.png

Top of Document [#table-of-contents]
.SS sc ping

Runs

.RS 4m
.EX
$ sc ping $server


.EE
.RE
.IP \(bu 2m
Where
.RS 2n
.IP \(bu 2m
\fB$server\fR is the domain part of the host value i\&.e\&. with the \fBusername@\fR removed\&.
.RE

!https://github\&.com/grizzlysmit/syscon/blob/main/docs/images/ping\&.png

by the \fBsc ping $key\fR

.RS 4m
.EX
multi sub MAIN('ping', Str:D $key \-\-> int){
    if ping($key) {
        return 0;
    } else {
        return 1;
    }
}


.EE
.RE
.P
Top of Document [#table-of-contents]
.SS sc get home

Get some files on the remote system and deposit them here (in the directory the user is currently in)\&.

.RS 4m
.EX
$ sc get home $key $files\-on\-remote\-system……


.EE
.RE
.P
!https://github\&.com/grizzlysmit/syscon/blob/main/docs/images/sc\-get\-home\&.png

Defined as 

.RS 4m
.EX
multi sub MAIN('get', 'home', Str:D $key, Bool :r(:$recursive) = False, *@args \-\-> int){
    if _get('home', $key, :$recursive, |@args) {
        return 0;
    } else {
        return 1;
    }
}


.EE
.RE
.P
Using the \fB_get(…)\fR function defined in \fBSyscon\&.rakumod\fR\&.

Top of Document [#table-of-contents]
.SS sc put home

.RS 4m
.EX
$ sc put home $key $files……


.EE
.RE
.IP \(bu 2m
Where
.RS 2n
.IP \(bu 2m
\fB$key\fR is as always the key to identify the host in question\&.
.RE
.RS 2n
.IP \(bu 2m
\fB$files\fR…… is a list of files to copy to the remote server\&.
.RE

!https://github\&.com/grizzlysmit/syscon/blob/main/docs/images/sc\-put\-home\&.png

Implemented as

.RS 4m
.EX
multi sub MAIN('put', 'home', Str:D $key, Bool :r(:$recursive) = False, *@args \-\-> int){
    if _put('home', $key, :$recursive, |@args) {
        return 0;
    } else {
        return 1;
    }
}


.EE
.RE
.IP \(bu 2m
Where
.RS 2n
.IP \(bu 2m
\fBmulti sub _put('home', Str:D $key, Bool :r(:$recursive) = False, *@args \-\- Bool) is export\fR> is a function in \fBSysycon\&.rakumod\fR
.RE

Top of Document [#table-of-contents]
.SS Utility functions
.SS sc edit configs

.RS 4m
.EX
$ sc edit configs


.EE
.RE
.P
Implemented by the \fBedit\-configs\fR function in the \fBGUI::Editors\&.rakumod\fR module\&. This open your config files in your preferred GUI editor, if you have one, if you don't have one of those setup it will try for a good substitute, failing that it will Fail and print an error message\&. 

Do not use this it's for experts only, instead use the \fBset\-*(…)\fR functions below\&.

.RS 4m
.EX
multi sub MAIN('edit', 'configs') returns Int {
   if edit\-configs() {
       exit 0;
   } else {
       exit 1;
   } 
}


.EE
.RE
.P
Top of Document [#table-of-contents]
