.pc
.TH Syscon.rakumod 1 2024-01-08
.SH module Syscon
.SS The Syscon library
.SS \fB$config\fR

.RS 4m
.EX
# config files
constant $config is export = "$home/\&.local/share/syscon";


.EE
.RE
.P
Top of Document [#table-of-contents]
.SS ssh(…)

.RS 4m
.EX
sub ssh(Str:D $key \-\-> Bool) is export 


.EE
.RE
.P
Top of Document [#table-of-contents]
.SS ping(…)

.RS 4m
.EX
sub ping(Str:D $key \-\-> Bool) is export 


.EE
.RE
.P
Top of Document [#table-of-contents]
.SS _get(…)

.RS 4m
.EX
multi sub _get('home', Str:D $key,
                Bool :r(:$recursive) = False,
                Str:D :$to = '\&.',
                *@args \-\-> Bool) is export 


.EE
.RE
.P
See sc get home [#sc-get-home]

Top of Document [#table-of-contents]
.SS _put(…)

.RS 4m
.EX
multi sub _put('home', Str:D $key,
                Bool :r(:$recursive) = False,
                Str:D :$to = '',
                *@args \-\-> Bool) is export 


.EE
.RE
.P
Top of Document [#table-of-contents]
